# Generated by Django 2.0.5 on 2018-05-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_activity', models.CharField(max_length=200)),
                ('ship', models.CharField(max_length=200)),
                ('core_no', models.CharField(max_length=200)),
                ('core_type', models.CharField(max_length=200)),
                ('total_length', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('depth', models.IntegerField()),
                ('core_condition', models.CharField(max_length=200)),
                ('date_described', models.DateField()),
                ('described_by', models.CharField(max_length=200)),
                ('physiographic_location', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
