# Generated by Django 2.0.5 on 2018-05-19 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='core',
            options={'verbose_name': 'Core', 'verbose_name_plural': 'Cores'},
        ),
        migrations.AlterModelOptions(
            name='fossils',
            options={'verbose_name': 'Fossil', 'verbose_name_plural': 'Fossils'},
        ),
        migrations.AlterModelOptions(
            name='strata',
            options={'verbose_name': 'Stratum', 'verbose_name_plural': 'Strata'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Survey', 'verbose_name_plural': 'Surveys'},
        ),
        migrations.AddField(
            model_name='strata',
            name='lithology',
            field=models.CharField(default=111, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bag',
            name='collected_by',
            field=models.CharField(max_length=25, null=True, verbose_name='Collected By'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='date_coll',
            field=models.DateField(verbose_name='Date Collected'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='lng',
            field=models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='sample_no',
            field=models.CharField(max_length=25, verbose_name='Sample No.'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cores.Survey', verbose_name='Survey No.'),
        ),
        migrations.AlterField(
            model_name='core',
            name='collected_by',
            field=models.CharField(max_length=25, null=True, verbose_name='Collected By'),
        ),
        migrations.AlterField(
            model_name='core',
            name='core_condition',
            field=models.CharField(max_length=25, verbose_name='Core Condition'),
        ),
        migrations.AlterField(
            model_name='core',
            name='core_type',
            field=models.CharField(max_length=25, verbose_name='Core Type'),
        ),
        migrations.AlterField(
            model_name='core',
            name='date_coll',
            field=models.DateField(verbose_name='Date Collected'),
        ),
        migrations.AlterField(
            model_name='core',
            name='date_described',
            field=models.DateField(verbose_name='Date Described'),
        ),
        migrations.AlterField(
            model_name='core',
            name='described_by',
            field=models.CharField(max_length=25, verbose_name='Described By'),
        ),
        migrations.AlterField(
            model_name='core',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='core',
            name='lng',
            field=models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='core',
            name='physiographic_location',
            field=models.CharField(max_length=25, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='core',
            name='sample_no',
            field=models.CharField(max_length=25, verbose_name='Sample No.'),
        ),
        migrations.AlterField(
            model_name='core',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cores.Survey', verbose_name='Survey No.'),
        ),
        migrations.AlterField(
            model_name='core',
            name='total_length',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Total Length'),
        ),
        migrations.AlterField(
            model_name='strata',
            name='core',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cores.Core', verbose_name='Core No.'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='field_activity',
            field=models.CharField(max_length=25, verbose_name='Field Activity'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='ship',
            field=models.CharField(max_length=25, verbose_name='Ship/Platform'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_no',
            field=models.CharField(max_length=25, verbose_name='Survey No.'),
        ),
    ]
