# Generated by Django 2.0.5 on 2018-05-15 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='core',
            name='description',
        ),
    ]
