# Generated by Django 2.0.5 on 2018-05-19 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0002_auto_20180518_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lithology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('alt_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterModelOptions(
            name='fossils',
            options={'verbose_name': 'Lithology', 'verbose_name_plural': 'Lithology'},
        ),
        migrations.RemoveField(
            model_name='fossils',
            name='comments',
        ),
        migrations.AlterField(
            model_name='strata',
            name='lithology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cores.Lithology'),
        ),
    ]
