# Generated by Django 2.0.5 on 2018-05-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0003_auto_20180514_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='total_length',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
