# Generated by Django 2.0.5 on 2018-05-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0004_auto_20180518_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boundaries',
            name='name',
        ),
        migrations.AddField(
            model_name='boundaries',
            name='boundary_type',
            field=models.CharField(choices=[('ANG', 'Angular'), ('DIF', 'Diffuse'), ('DIS', 'Distinct'), ('IRR', 'Irregular')], default='DIS', max_length=2, verbose_name='Boundary Type'),
        ),
        migrations.AddField(
            model_name='boundaries',
            name='position',
            field=models.DecimalField(decimal_places=3, default=111, max_digits=8),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='strata',
            name='boundaries',
        ),
        migrations.AddField(
            model_name='strata',
            name='boundaries',
            field=models.ManyToManyField(to='cores.Boundaries'),
        ),
    ]
