# Generated by Django 2.0.5 on 2018-05-19 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0005_auto_20180518_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundaries',
            name='boundary_type',
            field=models.CharField(choices=[('ANG', 'Angular'), ('DIF', 'Diffuse'), ('DIS', 'Distinct'), ('IRR', 'Irregular')], default='DIS', max_length=3, verbose_name='Boundary Type'),
        ),
        migrations.RemoveField(
            model_name='strata',
            name='boundaries',
        ),
        migrations.AddField(
            model_name='strata',
            name='boundaries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cores.Boundaries'),
        ),
    ]
