# Generated by Django 2.0.5 on 2018-05-19 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0006_auto_20180518_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strata',
            name='boundaries',
        ),
        migrations.AddField(
            model_name='boundaries',
            name='strata',
            field=models.ForeignKey(blank=True, default=111, on_delete=django.db.models.deletion.CASCADE, to='cores.Strata'),
            preserve_default=False,
        ),
    ]
