# Generated by Django 2.0.5 on 2018-05-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0007_auto_20180518_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='collected_by',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Collected By'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='date_coll',
            field=models.DateField(blank=True, verbose_name='Date Collected'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bag',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='boundaries',
            name='position',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='core',
            name='collected_by',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Collected By'),
        ),
        migrations.AlterField(
            model_name='core',
            name='core_condition',
            field=models.CharField(blank=True, max_length=25, verbose_name='Core Condition'),
        ),
        migrations.AlterField(
            model_name='core',
            name='core_type',
            field=models.CharField(blank=True, max_length=25, verbose_name='Core Type'),
        ),
        migrations.AlterField(
            model_name='core',
            name='date_coll',
            field=models.DateField(blank=True, verbose_name='Date Collected'),
        ),
        migrations.AlterField(
            model_name='core',
            name='date_described',
            field=models.DateField(blank=True, verbose_name='Date Described'),
        ),
        migrations.AlterField(
            model_name='core',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='core',
            name='described_by',
            field=models.CharField(blank=True, max_length=25, verbose_name='Described By'),
        ),
        migrations.AlterField(
            model_name='core',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='core',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='core',
            name='physiographic_location',
            field=models.CharField(blank=True, max_length=25, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='core',
            name='total_length',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, verbose_name='Total Length'),
        ),
        migrations.AlterField(
            model_name='fossils',
            name='abundance',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='fossils',
            name='alt_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='strata',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='field_activity',
            field=models.CharField(blank=True, max_length=25, verbose_name='Field Activity'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='ship',
            field=models.CharField(blank=True, max_length=25, verbose_name='Ship/Platform'),
        ),
    ]
