# Generated by Django 2.0.5 on 2018-05-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0008_auto_20180519_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='date_coll',
            field=models.DateField(blank=True, null=True, verbose_name='Date Collected'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='core',
            name='date_coll',
            field=models.DateField(blank=True, null=True, verbose_name='Date Collected'),
        ),
        migrations.AlterField(
            model_name='core',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='core',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude'),
        ),
    ]
