# Generated by Django 2.0.5 on 2018-05-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0009_auto_20180519_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='core_condition',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Core Condition'),
        ),
        migrations.AlterField(
            model_name='core',
            name='date_described',
            field=models.DateField(blank=True, null=True, verbose_name='Date Described'),
        ),
        migrations.AlterField(
            model_name='core',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
