# Generated by Django 2.0.5 on 2018-05-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0010_auto_20180519_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='core_condition',
            field=models.CharField(blank=True, default=111, max_length=25, verbose_name='Core Condition'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='core',
            name='total_length',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Total Length'),
        ),
    ]
