# Generated by Django 2.0.5 on 2018-05-19 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0011_auto_20180519_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='collected_by',
            field=models.CharField(blank=True, default=111, max_length=25, verbose_name='Collected By'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='core',
            name='collected_by',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=25, verbose_name='Collected By'),
            preserve_default=False,
        ),
    ]
