# Generated by Django 2.0.5 on 2018-06-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0013_strata_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strata',
            old_name='thickness',
            new_name='lower_bound',
        ),
        migrations.AddField(
            model_name='strata',
            name='upper_bound',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=8),
            preserve_default=False,
        ),
    ]
