# Generated by Django 2.0.5 on 2018-06-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0014_auto_20180605_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strata',
            name='color',
        ),
    ]
