# Generated by Django 2.0.5 on 2018-06-09 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0015_remove_strata_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSCL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Den1', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Wet Bulk Density (g/cm3')),
                ('MS1', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Magnetic Susceptibility (SI)')),
                ('core', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cores.Core', verbose_name='Core No.')),
            ],
            options={
                'verbose_name': 'MSCL',
                'verbose_name_plural': 'MSCL',
            },
        ),
    ]
