# Generated by Django 2.0.5 on 2018-06-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0017_auto_20180609_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mscl',
            old_name='Den1',
            new_name='den1',
        ),
        migrations.RenameField(
            model_name='mscl',
            old_name='MS1',
            new_name='ms1',
        ),
    ]
