# Generated by Django 2.0.5 on 2018-06-29 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0023_grainsize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grainsize',
            old_name='grave_pct',
            new_name='gravel_pct',
        ),
    ]
